server:
  port: 8082

spring:
  application:
    name: pet-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: false
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always